using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Fan : MonoBehaviour
{
    // Velocidad de rotaci贸n en grados por segundo
    public float rotationSpeed = 360f;

    public AudioSource fan;

    // Update is called once per frame
    void Update()
    {
        // Si se presiona la tecla "a"
        if (Input.GetKey(KeyCode.Space))
        {
            
            // Obtener la rotaci贸n actual
            Quaternion currentRotation = transform.localRotation;

            // Calcular la rotaci贸n acumulada basada en la velocidad y el tiempo
            float rotationAmount = rotationSpeed * Time.deltaTime;

            // Aplicar la rotaci贸n acumulada al eje Y
            transform.localRotation = currentRotation * Quaternion.Euler(0, rotationAmount, 0);
        }
        
        if (Input.GetKeyDown(KeyCode.Space))
        {
            fan.Play();
        }
        else if (Input.GetKeyUp(KeyCode.Space))
        {
            fan.Stop();
        }
    }
}

